### PR TITLE
Default the model path to current repository directory if not set

### LINKED ISSUE #89: Default the model path to current repository directory if not set
If the `MODEL_PATH` env var exists but has no value (i.e. empty or null), this causes the following commands to fail when running inside of the target repository pipeline:

```
git rm --ignore-unmatch "${MODEL_PATH}"/*.bpmn
git rm --ignore-unmatch "${MODEL_PATH}"/*.dmn
git rm --ignore-unmatch "${MODEL_PATH}"/*.form
```

They try to delete files in the root of the pipeline VM filesystem, and not the expected repository root folder.

The solution is to set the `MODEL_PATH` to the current dir (i.e. `.`) if not set to prevent the error from occurring, but it will still be up to the user of the extract and deploy functions to set the correct path longer term.

### PR DESCRIPTION
**Pull request by jphillips-bp3**
Sets the `MODEL_PATH` to the current directory (`.`) if the env var is not set for both the extract and deploy functions.

Unit tests have been added to test all situations, that the existing tests do not:
- `extract-1.sh`: This existing test does not set `MODEL_PATH` and therefore is set to `.` by default, but we are able to extract files to the root of the repository from WM. You will see in the console output the message `MODEL_PATH variable not set, defaulting to '.'`.
- `extract-fails-when-model-path-set-to-root.sh`: This new test sets `MODEL_PATH` to `/` to check that it fails when trying to write the process models to the root of the GitHub runner filesystem, which replicates other custom situations in other CI / CD platforms. In the GH pipeline logs you will see something like the following which is expected:
```bash
+ docker exec -i -w /local wmed /app/scripts/extractDeploy.sh extract
mode = 'extract'
Traceback (most recent call last):
  File "/app/scripts/extract.py", line 78, in <module>
    Extraction(args).main()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/app/scripts/extract.py", line 68, in main
    self.extract(project_items)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/app/scripts/extract.py", line 54, in extract
    with open(file_path, "w") as file:
         ~~~~^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '//process.bpmn'
```
- `deploy-1.sh`: This existing test does set `MODEL_PATH` and we are able to deploy files to Zeebe
- `deploy-when-model-path-set-to-default.sh`: This new test does not set `MODEL_PATH` and therefore is set to `.` by default, but we are able to deploy to Zeebe from the root of the repository. You will see in the console output the message `MODEL_PATH variable not set, defaulting to '.'`.

### CODE REVIEW

File: scripts/deploy.sh [hunk 1]
```diff
@@ -29,4 +29,9 @@ if [ -z "$NO_GIT" ] && [ -z "$NO_GIT_FETCH" ]; then
   git -c advice.detachedHead=false checkout "${GIT_REF}"
 fi
 
+if [ "$MODEL_PATH" = "" ]; then
+  MODEL_PATH=.
+  echo "Defaulting the model path to '.' as the variable exists but is not set"
```
Comment (bschlosser) [inline scripts/deploy.sh]:
```suggestion
  echo "MODEL_PATH variable not set, defaulting to '.'"
```

(Same for extract.sh:29)

File: integration-tests/tests/extract-fails-when-model-path-set-to-root.sh [hunk 2]
```diff
@@ -0,0 +1,116 @@
...
+    -e CAMUNDA_WM_PROJECT="$project_id" \
+    -e CAMUNDA_WM_HOST="localhost:8070" \
+    -e NO_GIT_SETUP=true \
+    -e CICD_BRANCH="$IMAGE_REF" \
+    -e CICD_ACCESS_TOKEN=dummy \
+    -e CICD_REPOSITORY_PATH="$GITHUB_WORKSPACE" \
+    -e CICD_SERVER_HOST="$GITHUB_SERVER_URL/$GITHUB_REPOSITORY" \
+    -e GIT_USERNAME="$GITHUB_ACTOR" \
+    -e GIT_USER_EMAIL="$GITHUB_ACTOR_ID+$GITHUB_ACTOR@users.noreply.github.com" \
+      --entrypoint /bin/sh $IMAGE_NAME:$IMAGE_REF
```
Comment (bschlosser) [inline integration-tests/tests/extract-fails-when-model-path-set-to-root.sh:85]: This maybe a copy from somewhere else, but why are we overriding the entry point, and then calling the script directly below?

Comment (jphillips-bp3) [reply integration-tests/tests/extract-fails-when-model-path-set-to-root.sh:85]: This is copied over from the `extract-1.sh` tests, which there was a good reason in that test. This PR is still in draft however so things are still WIP.

Comment (jphillips-bp3) [reply integration-tests/tests/extract-fails-when-model-path-set-to-root.sh:85]: @bschlosser But actually there is a good reason to do this here as well. If we run the container as you suggest it will complete and the container will exit. I need to be able to run the `extractDeploy.sh` so I can check the `MODEL_PATH` env var is then set whilst the container is still running, and its environment variables are available. Unless there is another way?

Comment (jphillips-bp3) [reply integration-tests/tests/extract-fails-when-model-path-set-to-root.sh:85]: The crucial bit is being able to be in interactive mode whilst running the script and performing the env var check.

Comment (bschlosser) [reply integration-tests/tests/extract-fails-when-model-path-set-to-root.sh:85]: That makes sense. Might be worth a small comment in the script, so that in 6 months when one of us looks at it again we don't ask why not to use the default entry point again :-)

**Comment by jphillips-bp3** [comment]
@joewarner @bschlosser 

This is ready for review.

@joewarner I know we spoke about having a way of saying if a test can fail legitimately, but this was not needed in the end, as this is checked via this `assert_equals`: https://github.com/BP3/wm-extract-deploy/blob/bc3727c82190c21e3ede5f695f0391cb39f8d292/integration-tests/tests/extract-fails-when-model-path-set-to-root.sh#L98

File: integration-tests/tests/extract-1.sh [hunk 3]
```diff
@@ -100,13 +100,13 @@ When () {
...
   # So, although this command demonstrates how we might normally run the command it is actually
   # the following command below that will allow us to grab the data
-  docker run --rm --net=host \
-    -e NO_GIT=true \
-    -e OAUTH2_CLIENT_ID=wmed -e OAUTH2_CLIENT_SECRET=wmed \
-    -e OAUTH2_TOKEN_URL=http://localhost:18080/auth/realms/camunda-platform/protocol/openid-connect/token \
-    -e CAMUNDA_WM_PROJECT="$project_id" \
-    -e CAMUNDA_WM_HOST="localhost:8070" \
-      $IMAGE_NAME:$IMAGE_REF extract
+#  docker run --rm --net=host \
```
Comment (bschlosser) [inline integration-tests/tests/extract-1.sh]: Can this be removed? Was it temporarily commented out, or is it not needed anymore? Does the comment above still apply?

Comment (jphillips-bp3) [reply integration-tests/tests/extract-1.sh]: Its not needed, but more of a reference to how the Docker run is normally run, but not in this situation and why, in case someone is wondering.

But I will remove it.

File: integration-tests/tests/deploy-when-model-path-set-to-default.sh [hunk 4]
```diff
@@ -0,0 +1,128 @@
...
+  cp files/*.bpmn $TESTSDIR/$TESTNAME
+
+  get_access_token
+}
+
+When () {
+  echo "$TESTNAME: When"
+  mkdir -p $TESTSDIR/$TESTNAME
+
+  # The mount command won't work properly when using dind!
```
Comment (bschlosser) [inline integration-tests/tests/deploy-when-model-path-set-to-default.sh]: You simplified this comment in the other two files. Seems like the same should be done here

File: integration-tests/tests/extract-fails-when-model-path-set-to-root.sh [hunk 5]
```diff
@@ -0,0 +1,110 @@
...
+  # as that test case is handled in other tests
+  create_project "Project"
+  create_file process $project_id files/process.bpmn bpmn
+}
+
+When () {
+  echo "$TESTNAME: When"
+  mkdir -p $TESTSDIR/$TESTNAME
+
+  # Running this in interactive mode so we can run the extract script and check for the MODEL_PATH
```
Comment (bschlosser) [inline integration-tests/tests/extract-fails-when-model-path-set-to-root.sh]: Is this comment still correct about checking MODEL_PATH?

File: integration-tests/tests/deploy-1.sh [hunk 6]
```diff
@@ -70,18 +70,8 @@ When () {
...
-#  docker run --rm --net=host --mount type=bind,src=${PWD},dst=/local --workdir /local \
-#    -e NO_GIT=true \
-#    -e OAUTH2_CLIENT_ID=$CLIENT_ID -e OAUTH2_CLIENT_SECRET=$CLIENT_SECRET \
-#    -e OAUTH2_TOKEN_URL=http://localhost:18080/auth/realms/camunda-platform/protocol/openid-connect/token \
-#    -e CLUSTER_HOST=localhost \
-#    -e MODEL_PATH=./files \
-#      $IMAGE_NAME:$IMAGE_REF deploy
-
+  # The mount command won't work properly when using dind, so we have to do it this way to allow us to grab
+  # Also it allows us to call the extractDeploy.sh script interactively otherwise the container will run and complete
```
Comment (joewarner) [inline integration-tests/tests/deploy-1.sh:75]: The first line of this comment just seems to trail off and not quite [get to the point]

File: integration-tests/tests/deploy-when-model-path-set-to-default.sh [hunk 7]
```diff
@@ -0,0 +1,118 @@
...
+
+  get_access_token
+}
+
+When () {
+  echo "$TESTNAME: When"
+  mkdir -p $TESTSDIR/$TESTNAME
+
+  # The mount command won't work properly when using dind, so we have to do it this way to allow us to grab
+  # Also it allows us to call the extractDeploy.sh script interactively otherwise the container will run and complete
```
Comment (joewarner) [inline integration-tests/tests/deploy-when-model-path-set-to-default.sh:74]: First line of this comment is cut/pasted and has the same problem.

File: integration-tests/tests/extract-1.sh [hunk 8]
```diff
@@ -96,19 +96,8 @@ When () {
...
-    -e NO_GIT=true \
-    -e OAUTH2_CLIENT_ID=wmed -e OAUTH2_CLIENT_SECRET=wmed \
-    -e OAUTH2_TOKEN_URL=http://localhost:18080/auth/realms/camunda-platform/protocol/openid-connect/token \
-    -e CAMUNDA_WM_PROJECT="$project_id" \
-    -e CAMUNDA_WM_HOST="localhost:8070" \
-      $IMAGE_NAME:$IMAGE_REF extract
-
-  # Unfortunately the command above doesn't allow us to grab the data - but doing it this way we can
+  # The mount command won't work properly when using dind, so we have to do it this way to allow us to grab
+  # Also it allows us to call the extractDeploy.sh script interactively otherwise the container will run and complete
```
Comment (joewarner) [inline integration-tests/tests/extract-1.sh:101]: Same cut/paste problem with the comment

File: integration-tests/tests/extract-fails-when-model-path-set-to-root.sh [hunk 9]
```diff
@@ -0,0 +1,110 @@
...
+  create_project "Project"
+  create_file process $project_id files/process.bpmn bpmn
+}
+
+When () {
+  echo "$TESTNAME: When"
+  mkdir -p $TESTSDIR/$TESTNAME
+
+  # The mount command won't work properly when using dind, so we have to do it this way to allow us to grab
+  # Also it allows us to call the extractDeploy.sh script interactively otherwise the container will run and complete
```
Comment (joewarner) [inline integration-tests/tests/extract-fails-when-model-path-set-to-root.sh:76]: Cut/Paste comment needs fixing.

File: integration-tests/tests/deploy-1.sh (hunk 6 above)
Comment (joewarner) [reply integration-tests/tests/deploy-1.sh:75]: How do you claim this is resolved?

Comment (jphillips-bp3) [reply integration-tests/tests/deploy-1.sh:75]: @joewarner Because its there! See lines 73 and 74: https://github.com/BP3/wm-extract-deploy/blob/6cae02bd865701e0b2605670c6022290867fe6e5/integration-tests/tests/deploy-1.sh#L73C3-L73C32

Its not the first time I have seen GH (and GL) MR's not refreshing when new commits are pushed.

**Review by joewarner — APPROVED** [review]
